---
- hosts: all
  become: true

  vars:
    myuser: francisco
  
  tasks:
    
    # cria o usuário deploy setando uma senha randomica e salvando em um diretório na máquina de controle
    - name: Create deploy user, save random password in pw.txt
      become: true
      user:
        name: deploy
        password: "{{ lookup('password', 'pw.txt encrypt=sha512_crypt') }}"