
---
- hosts: all
  become: true

  tasks:

    - name: Download goss binary
      delegate_to: localhost
      connection: local
      become: false
      get_url:
        url: "https://oreil.ly/RuRsL"
        dest: "~/Downloads/goss"
        mode: '0755'
      ignore_errors: true


    - name: Escreve na máquina de controle o arquivo com nome do host
      delegate_to: localhost
      connection: local
      become: false
      ansible.builtin.file:
        path: "/tmp/{{ ansible_hostname }}.conf"
        state: touch
        mode: u=rw,g=r,o=r
      ignore_errors: true

    - name: Escreve na máquina de controle o arquivo com nome do host
      delegate_to: host02
      become: false
      ansible.builtin.file:
        path: "/tmp/{{ ansible_hostname }}-teste.conf"
        state: touch
        mode: u=rw,g=r,o=r
      ignore_errors: true