---
- hosts: all
  become: true

  vars:
    myuser: francisco
  
  tasks:
    
    # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_loops.html

    - name: Add several users
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
        groups: "{{ item.groups }}"
      loop:
        - { name: 'testuser1', groups: 'adm' }
        - { name: 'testuser2', groups: 'root' }


    - name: Iterate with loop
      debug:
        msg: "KPI: {{ item.kpi }} prio: {{ i + 1 }} goto: {{ item.dept }}"
      loop:
        - kpi: availability
          dept: operations
        - kpi: performance
          dept: development
        - kpi: security
          dept: security
      loop_control:
        index_var: i
        pause: 3 # pausa de 3 segundos entre as iterações


    - name: Iterate over lines in a file
      debug:
        msg: "{{ item }}"
      with_lines:
        - cat files/turing.txt


    - name: Add public keys to account
      become: true
      authorized_key:
        user: deploy
        key: "{{ lookup('file', item) }}"
      with_fileglob:
        - files/*.pub


    - name: Iterate over ansible_enp0s8
      debug:
        msg: "{{ item.key }}={{ item.value }}"
      with_dict: "{{ ansible_enp0s8.ipv4 }}"