- name: deploy mezzanine on web
  hosts: web
  debugger: always

  tasks:

  - name: Teste
    debug:
      var: ansible_facts

  - name: Install apt packages
    become: true
    apt:
      update_cache: true
      cache_valid_time: 3600
      pkg:
        - acl
        - git